// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Noxtend.Infrastructure.Persistence;

#nullable disable

namespace Noxtend.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(NoxtendDbContext))]
    [Migration("20260902141611_RevertCharacterDecomposeFigureAnchoredBounds")]
    partial class RevertCharacterDecomposeFigureAnchoredBounds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Noxtend.Domain.Job.PipelineJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Gender")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("ImageModel")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid?>("ImageProviderConfigId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MeshModel")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid?>("MeshProviderConfigId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PartHints")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RequiresReview")
                        .HasColumnType("bit");

                    b.Property<bool>("ReviewApproved")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Scene")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SceneJson");

                    b.Property<Guid>("SourceImageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.PrimitiveCollection<string>("_descriptionsStale")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DescriptionsStale");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending();

                    b.HasIndex("Category", "CreatedAt")
                        .IsDescending(false, true);

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("Jobs", (string)null);
                });

            modelBuilder.Entity("Noxtend.Domain.Mesh.MeshRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("CreditsConsumed")
                        .HasColumnType("int");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("LastProviderCode")
                        .HasColumnType("int");

                    b.Property<string>("LastProviderRequestId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("ModelSeed")
                        .HasColumnType("int");

                    b.Property<Guid>("PartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Progress")
                        .HasColumnType("int");

                    b.Property<Guid>("ProviderConfigId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProviderTaskId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("RunNumber")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TextureSeed")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ProviderTaskId")
                        .IsUnique()
                        .HasFilter("[ProviderTaskId] IS NOT NULL");

                    b.HasIndex("TaskId", "RunNumber")
                        .IsUnique();

                    b.HasIndex("JobId", "PartId", "RunNumber")
                        .IsDescending(false, false, true);

                    b.ToTable("MeshRuns", null, t =>
                        {
                            t.HasCheckConstraint("CK_MeshRuns_Progress", "[Progress] BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("Noxtend.Domain.Provider.ProviderConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApiKeyCipher")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApiKeyLast4")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("ProviderConfigs", (string)null);
                });

            modelBuilder.Entity("Noxtend.Domain.Scene.SceneLayout", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ComposedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SourceMeshCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JobId")
                        .IsUnique();

                    b.ToTable("SceneLayouts", (string)null);
                });

            modelBuilder.Entity("Noxtend.Domain.Upload.StoredImage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BlobKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("StoredImages", (string)null);
                });

            modelBuilder.Entity("Noxtend.Tuning.Domain.Call.LlmCall", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("InputTokens")
                        .HasColumnType("int");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("LatencyMs")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int?>("OutputImages")
                        .HasColumnType("int");

                    b.Property<int?>("OutputTokens")
                        .HasColumnType("int");

                    b.Property<Guid>("PromptVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProviderConfigId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RequestPayload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponsePayload")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("bit");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("TaskId");

                    b.HasIndex("Kind", "At");

                    b.ToTable("LlmCalls", (string)null);
                });

            modelBuilder.Entity("Noxtend.Tuning.Domain.Call.ModelPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("InputPerMillion")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<int?>("LongContextFrom")
                        .HasColumnType("int");

                    b.Property<decimal?>("LongInputPerMillion")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("LongOutputPerMillion")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("OutputPerMillion")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("PerImage")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("Id");

                    b.HasIndex("Model", "EffectiveFrom")
                        .IsUnique()
                        .HasDatabaseName("IX_ModelPrices_ModelEffectiveFrom");

                    b.ToTable("ModelPrices", (string)null);
                });

            modelBuilder.Entity("Noxtend.Tuning.Domain.Golden.GoldenSample", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ExpectedNote")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("StoredImageId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StoredImageId")
                        .IsUnique();

                    b.ToTable("GoldenSamples", (string)null);
                });

            modelBuilder.Entity("Noxtend.Tuning.Domain.Golden.Verdict", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsPass")
                        .HasColumnType("bit");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Memo")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("JobId")
                        .IsUnique();

                    b.ToTable("Verdicts", (string)null);
                });

            modelBuilder.Entity("Noxtend.Tuning.Domain.Prompt.PromptVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("JsonSchema")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("System")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Kind", "Category")
                        .IsUnique()
                        .HasDatabaseName("IX_PromptVersions_ActiveByKindCategory")
                        .HasFilter("[IsActive] = 1");

                    b.HasIndex("Kind", "Category", "Version")
                        .IsUnique()
                        .HasDatabaseName("IX_PromptVersions_Kind_Version");

                    b.ToTable("PromptVersions", (string)null);
                });

            modelBuilder.Entity("Noxtend.Domain.Job.PipelineJob", b =>
                {
                    b.OwnsMany("Noxtend.Domain.Job.AssetPart", "Parts", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Category")
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)");

                            b1.Property<int?>("DepthOrder")
                                .HasColumnType("int");

                            b1.Property<string>("Description")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<Guid?>("GeneratedImageId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("IsManuallyAdded")
                                .HasColumnType("bit");

                            b1.Property<Guid>("JobId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)");

                            b1.PrimitiveCollection<string>("OccludedBy")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("Ordinal")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.HasIndex("JobId");

                            b1.ToTable("AssetParts", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("JobId");

                            b1.OwnsMany("Noxtend.Domain.Job.PartPlacement", "_placements", b2 =>
                                {
                                    b2.Property<Guid>("AssetPartId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("Ordinal")
                                        .HasColumnType("int");

                                    b2.HasKey("AssetPartId", "Ordinal");

                                    b2.ToTable("PartPlacements", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("AssetPartId");

                                    b2.OwnsOne("Noxtend.Domain.Job.Bounds", "Bounds", b3 =>
                                        {
                                            b3.Property<Guid>("PartPlacementAssetPartId")
                                                .HasColumnType("uniqueidentifier");

                                            b3.Property<int>("PartPlacementOrdinal")
                                                .HasColumnType("int");

                                            b3.Property<double>("H")
                                                .HasColumnType("float")
                                                .HasColumnName("H");

                                            b3.Property<double>("W")
                                                .HasColumnType("float")
                                                .HasColumnName("W");

                                            b3.Property<double>("X")
                                                .HasColumnType("float")
                                                .HasColumnName("X");

                                            b3.Property<double>("Y")
                                                .HasColumnType("float")
                                                .HasColumnName("Y");

                                            b3.HasKey("PartPlacementAssetPartId", "PartPlacementOrdinal");

                                            b3.ToTable("PartPlacements");

                                            b3.WithOwner()
                                                .HasForeignKey("PartPlacementAssetPartId", "PartPlacementOrdinal");
                                        });

                                    b2.Navigation("Bounds")
                                        .IsRequired();
                                });

                            b1.Navigation("_placements");
                        });

                    b.OwnsMany("Noxtend.Domain.Job.GeneratedImage", "GeneratedImages", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("BlobKey")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("nvarchar(512)");

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("datetimeoffset");

                            b1.Property<Guid>("JobId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("PartId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<long>("SizeBytes")
                                .HasColumnType("bigint");

                            b1.Property<Guid>("TaskId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("ViewDirection")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("nvarchar(16)");

                            b1.HasKey("Id");

                            b1.HasIndex("JobId");

                            b1.HasIndex("PartId");

                            b1.ToTable("GeneratedImages", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("JobId");
                        });

                    b.OwnsMany("Noxtend.Domain.Job.GeneratedMesh", "GeneratedMeshes", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("datetimeoffset");

                            b1.Property<int?>("CreditsConsumed")
                                .HasColumnType("int");

                            b1.Property<Guid>("JobId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("MeshRunId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("PartId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("TaskId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("JobId");

                            b1.HasIndex("PartId", "CreatedAt")
                                .IsDescending(false, true);

                            b1.ToTable("GeneratedMeshes", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("JobId");

                            b1.OwnsMany("Noxtend.Domain.Mesh.MeshArtifact", "Artifacts", b2 =>
                                {
                                    b2.Property<Guid>("GeneratedMeshId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("Kind")
                                        .HasMaxLength(16)
                                        .HasColumnType("nvarchar(16)");

                                    b2.Property<string>("BlobKey")
                                        .IsRequired()
                                        .HasMaxLength(512)
                                        .HasColumnType("nvarchar(512)");

                                    b2.Property<string>("ContentType")
                                        .IsRequired()
                                        .HasMaxLength(64)
                                        .HasColumnType("nvarchar(64)");

                                    b2.Property<DateTimeOffset>("CreatedAt")
                                        .HasColumnType("datetimeoffset");

                                    b2.Property<long>("SizeBytes")
                                        .HasColumnType("bigint");

                                    b2.HasKey("GeneratedMeshId", "Kind");

                                    b2.ToTable("GeneratedMeshArtifacts", null, t =>
                                        {
                                            t.HasCheckConstraint("CK_GeneratedMeshArtifacts_Size", "[SizeBytes] > 0");
                                        });

                                    b2.WithOwner()
                                        .HasForeignKey("GeneratedMeshId");
                                });

                            b1.Navigation("Artifacts");
                        });

                    b.OwnsMany("Noxtend.Domain.Job.PipelineTask", "Tasks", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("AttemptCount")
                                .HasColumnType("int");

                            b1.Property<DateTimeOffset?>("CompletedAt")
                                .HasColumnType("datetimeoffset");

                            b1.Property<Guid?>("DependsOnTaskId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("FailureReason")
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)");

                            b1.Property<Guid>("JobId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)");

                            b1.Property<DateTimeOffset?>("LeaseExpiresAt")
                                .HasColumnType("datetimeoffset");

                            b1.Property<string>("MeshInputs")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("MeshInputsJson");

                            b1.Property<string>("Model")
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)");

                            b1.Property<DateTimeOffset?>("NotBefore")
                                .HasColumnType("datetimeoffset");

                            b1.Property<int>("Ordinal")
                                .HasColumnType("int");

                            b1.Property<Guid?>("PartId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid?>("ProviderConfigId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<byte[]>("RowVersion")
                                .IsConcurrencyToken()
                                .ValueGeneratedOnAddOrUpdate()
                                .HasColumnType("rowversion");

                            b1.Property<DateTimeOffset?>("StartedAt")
                                .HasColumnType("datetimeoffset");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)");

                            b1.Property<string>("ViewDirection")
                                .HasMaxLength(16)
                                .HasColumnType("nvarchar(16)");

                            b1.HasKey("Id");

                            b1.HasIndex("JobId");

                            b1.HasIndex("PartId");

                            b1.HasIndex("PartId", "Kind")
                                .IsUnique()
                                .HasFilter("[Kind] = 'Reconstruct'");

                            b1.HasIndex("Status", "Kind");

                            b1.HasIndex("Status", "LeaseExpiresAt");

                            b1.ToTable("Tasks", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("JobId");
                        });

                    b.Navigation("GeneratedImages");

                    b.Navigation("GeneratedMeshes");

                    b.Navigation("Parts");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Noxtend.Domain.Mesh.MeshRun", b =>
                {
                    b.OwnsMany("Noxtend.Domain.Mesh.MeshArtifact", "Artifacts", b1 =>
                        {
                            b1.Property<Guid>("MeshRunId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Kind")
                                .HasMaxLength(16)
                                .HasColumnType("nvarchar(16)");

                            b1.Property<string>("BlobKey")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)");

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("datetimeoffset");

                            b1.Property<long>("SizeBytes")
                                .HasColumnType("bigint");

                            b1.HasKey("MeshRunId", "Kind");

                            b1.ToTable("MeshRunArtifacts", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("MeshRunId");
                        });

                    b.OwnsMany("Noxtend.Domain.Mesh.MeshRunInput", "Inputs", b1 =>
                        {
                            b1.Property<Guid>("MeshRunId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("ViewDirection")
                                .HasMaxLength(16)
                                .HasColumnType("nvarchar(16)");

                            b1.Property<Guid>("GeneratedImageId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTimeOffset?>("PreparedAt")
                                .HasColumnType("datetimeoffset");

                            b1.Property<string>("ProviderFileToken")
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)");

                            b1.Property<string>("SourceContentType")
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)");

                            b1.Property<string>("UploadContentType")
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)");

                            b1.HasKey("MeshRunId", "ViewDirection");

                            b1.ToTable("MeshRunInputs", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("MeshRunId");
                        });

                    b.Navigation("Artifacts");

                    b.Navigation("Inputs");
                });

            modelBuilder.Entity("Noxtend.Domain.Scene.SceneLayout", b =>
                {
                    b.OwnsMany("Noxtend.Domain.Scene.SceneInstance", "_instances", b1 =>
                        {
                            b1.Property<Guid>("SceneLayoutId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("PartId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Ordinal")
                                .HasColumnType("int");

                            b1.Property<double>("RotationY")
                                .HasColumnType("float");

                            b1.Property<double>("Scale")
                                .HasColumnType("float");

                            b1.Property<double>("X")
                                .HasColumnType("float");

                            b1.Property<double>("Y")
                                .HasColumnType("float");

                            b1.Property<double>("Z")
                                .HasColumnType("float");

                            b1.HasKey("SceneLayoutId", "PartId", "Ordinal");

                            b1.ToTable("SceneInstances", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("SceneLayoutId");
                        });

                    b.Navigation("_instances");
                });
#pragma warning restore 612, 618
        }
    }
}
