// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Noxtend.Infrastructure.Persistence;

#nullable disable

namespace Noxtend.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(NoxtendDbContext))]
    [Migration("20260728120402_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Noxtend.Domain.Job.PipelineJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ConsistencyPrompt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("SourceImageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending();

                    b.HasIndex("Category", "CreatedAt")
                        .IsDescending(false, true);

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("Jobs", (string)null);
                });

            modelBuilder.Entity("Noxtend.Domain.Provider.ProviderConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApiKeyCipher")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApiKeyLast4")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("ProviderConfigs", (string)null);
                });

            modelBuilder.Entity("Noxtend.Domain.Upload.StoredImage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BlobKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("StoredImages", (string)null);
                });

            modelBuilder.Entity("Noxtend.Domain.Job.PipelineJob", b =>
                {
                    b.OwnsMany("Noxtend.Domain.Job.AssetPart", "Parts", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("JobId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)");

                            b1.Property<int>("Ordinal")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.HasIndex("JobId");

                            b1.ToTable("AssetParts", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("JobId");
                        });

                    b.OwnsMany("Noxtend.Domain.Job.PipelineTask", "Tasks", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("AttemptCount")
                                .HasColumnType("int");

                            b1.Property<DateTimeOffset?>("CompletedAt")
                                .HasColumnType("datetimeoffset");

                            b1.Property<Guid?>("DependsOnTaskId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("FailureReason")
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)");

                            b1.Property<Guid>("JobId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)");

                            b1.Property<DateTimeOffset?>("LeaseExpiresAt")
                                .HasColumnType("datetimeoffset");

                            b1.Property<int>("Ordinal")
                                .HasColumnType("int");

                            b1.Property<Guid?>("ProviderConfigId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTimeOffset?>("StartedAt")
                                .HasColumnType("datetimeoffset");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)");

                            b1.HasKey("Id");

                            b1.HasIndex("JobId");

                            b1.HasIndex("Status", "Kind");

                            b1.HasIndex("Status", "LeaseExpiresAt");

                            b1.ToTable("Tasks", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("JobId");
                        });

                    b.Navigation("Parts");

                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
